Repository asciidwango/js-primer, pull requests merged in 2020-06, with the labels that each got.

#1174 fix: use GitHon instead of GitBook
  .github/workflows/test.yml
  .npmrc
  package-lock.json
  package.json
  resources/gitbook-plugin-include-codeblock.hbs
  tools/gitbook/copy-favicon.js
Labels: Status: Review Needed

#1187 feat(function-this): globalThisについて追加
  source/basic/function-this/README.md
Labels: Type: Feature

#1188 chone: fix typo
  source/basic/async/README.md
Labels: Type: Need to Publish

#1194 fix(loop): for...in文についてのES2020の変更点を反映
  source/basic/loop/README.md
Labels: Lang: ES2020
