Repository asciidwango/js-primer, pull requests merged in 2023-07, with the labels that each got.

#1675 feat: Array.prototype.{findLast, findLastIndex}の追加
  source/basic/array/README.md
  test/markdown-doc-test.js
Labels: Type: Feature

#1676 #1650 匿名関数 → 無名関数 に変更
  prh.yml
  source/basic/class/README.md
  source/basic/function-declaration/README.md
  source/basic/function-scope/README.md
  source/basic/function-this/README.md
  source/basic/loop/README.md
  source/basic/statement-expression/README.md
Labels: Type: Refactoring

#1680 fix: update power-doctest and remove vm2
  package-lock.json
  package.json
  test/lib/testing-code.js
Labels: Type: Refactoring

#1679 feat(array): Change Array by copyの対応
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  source/basic/array/README.md
  source/basic/variables/README.md
  test/markdown-doc-test.js
Labels: Type: Feature, Lang: ES2023
