Repository asciidwango/js-primer, pull requests merged in 2023-01, with the labels that each got.

#1548 fix: .nvmrc を v18.12.0 へと更新
  .nvmrc
Labels: Type: Meta

#1549 fix: 連続する「人によって」を修正
  source/basic/introduction/README.md
Labels: Type: Need to Publish

#1551 fix: typo を修正
  source/basic/variables/README.md
Labels: Type: Need to Publish

#1552 fix: 冗長な表現を修正
  source/basic/variables/README.md
  source/basic/variables/src/let-duplicated-define-invalid.js
Labels: Type: Need to Publish

#1554 fix(basic): 冗長な文の修正、fix typo
  source/basic/function-declaration/README.md
Labels: Type: Errata, Type: Need to Publish

#1558 fix typo
  source/intro/preparation/README.md
Labels: Type: Need to Publish

#1557 fix: 剰余演算子の説明を改善
  source/basic/operator/README.md
Labels: Type: Errata, Type: Need to Publish
