Repository asciidwango/js-primer, pull requests merged in 2023-02, with the labels that each got.

#1560 feat : for..ofの説明からGenerator関数の説明を削除
  source/basic/loop/README.md
Labels: Type: Need to Publish

#1561 chore: rename .nvmrc to .node-version
  .node-version
  netlify.toml
Labels: Type: WebSite, Type: Refactoring

#1562 fix: 9 の二進数表現の誤りを修正
  source/basic/operator/README.md
Labels: Type: Bug, Type: Errata, Type: Need to Publish

#1567 refactor: Update to Node.js 18.14.0 and npm 9.3.1
  .node-version
  README.md
  book.json
  package-lock.json
  package.json
  source/intro/README.md
  source/use-case/nodecli/argument-parse/src/package-lock.json
  source/use-case/nodecli/md-to-html/src/package-lock.json
  source/use-case/nodecli/package-lock.json
  source/use-case/nodecli/read-file/src/package-lock.json
  source/use-case/nodecli/refactor-and-unittest/src/package-lock.json
Labels: Type: ユースケース, Type: Need to Publish

#1571 「暗黙的な型変換」の文脈において助詞「を」が抜けている箇所を修正した
  source/basic/implicit-coercion/README.md
  source/basic/operator/README.md
Labels: Type: Errata, Type: Need to Publish

#1572 fix: 「文と式」における不要な読点を削除
  source/basic/statement-expression/README.md
Labels: Type: Need to Publish

#1575 fix: 「条件分岐」の章において、それよりも前の章が後の章であるかのように表現されているため、修正
  source/basic/condition/README.md
Labels: Type: Errata, Type: Need to Publish

#1576 fix: 「条件分岐」において、まとめの中の break 文の説明にみだれがあるため、読みやすく改善
  source/basic/condition/README.md
Labels: Type: Errata, Type: Need to Publish

#1577 fix: 「第一部: 基本文法」目次の言い回しの改善
  source/basic/README.md
Labels: Type: Errata, Type: Need to Publish

#1578 fix: 「文と式」におけるセクションのタイトルを漢字に変更
  source/basic/statement-expression/README.md
Labels: Type: Need to Publish

#1584 「関数と宣言」のまとめに記載されている順番を本文の順番に対応させた
  source/basic/function-declaration/README.md
Labels: Type: Need to Publish

#1585 constで定義したオブジェクトへの再代入で発生する例外を修正した
  source/basic/object/README.md
Labels: Type: Errata, Type: Need to Publish

#1586 fix: 「文字列」における誤字などの修正
  source/basic/string/README.md
Labels: Type: Errata, Type: Need to Publish

#1593 2023-01-12と2023-02-16のミーティングノート
  meetings/2023-01-12/README.md
  meetings/2023-02-16/README.md
Labels: Type: Meta

#1597 fix: 「ラッパーオブジェクト」におけるオブジェクトをもつプリミティブ型の記述に BigInt を追加
  source/basic/wrapper-object/README.md
Labels: Type: Errata, Type: Need to Publish

#1596 fix: 「文字列とUnicode」における脱字の修正
  source/basic/string-unicode/README.md
Labels: Type: Errata, Type: Need to Publish

#1587 fix: リンクが貼られていなかったため、修正
  source/basic/read-eval-print/README.md
Labels: Type: Errata

#1588 fix: 「演算子」の章を読みやすく改善
  source/basic/operator/README.md
Labels: Type: Errata, Type: Need to Publish

#1595 fix: 「関数とthis」における文の乱れを修正
  source/basic/function-this/README.md
Labels: Type: Errata, Type: Need to Publish

#1599 fix: 「例外処理」における誤字修正
  prh.yml
  source/basic/error-try-catch/README.md
Labels: Type: Errata, Type: Need to Publish

#1598 fix: 「クラス」における誤字修正や説明の改善
  source/basic/class/README.md
Labels: Type: Errata, Type: Need to Publish

#1604 何も出力されないコードのため､実行ボタンを削除
  source/basic/loop/README.md
Labels: Type: Refactoring

#1603 暗黙的型変換で isNaN 関数についての脚注を追加
  source/basic/implicit-coercion/README.md
Labels: Status: Review Needed, Type: Feature

#1594 fix: 「関数とスコープ」における誤字脱字の訂正など
  source/basic/function-scope/README.md
Labels: Type: Errata, Type: Need to Publish

#1608 アクセサプロパティをアクセッサプロパティへと統一するように修正した
  source/basic/class/README.md
Labels: Type: Errata, Type: Need to Publish

#1607 関数と宣言: デフォルト引数の説明で文言を一部修正した
  source/basic/function-declaration/README.md
Labels: Type: Errata, Type: Need to Publish

#1615 fix: 「ECMAScriptモジュール」において console.log の内容が誤っている箇所を修正
  source/basic/module/src/named-import.js
Labels: Type: Errata, Type: Need to Publish

#1617 fix(module): remove quote from function bar
  source/basic/module/src/named-import.js
Labels: Type: Errata, Type: Need to Publish

#1614 fix: 「第一部: おわりに」で文体が謙譲表現となっている箇所を修正
  source/basic/other-parts/README.md
Labels: Type: Refactoring, Type: Need to Publish

#1619 fix: 「非同期処理」における typo 修正
  source/basic/async/README.md
Labels: Type: Errata, Type: Need to Publish

#1621 fix: 「エントリーポイント」におけるコメント内の不要スペースを削除
  source/use-case/ajaxapp/entrypoint/README.md
Labels: Type: Refactoring

#1620 fix: 「アプリケーション開発の準備」における typo 修正
  source/use-case/setup-local-env/README.md
Labels: Type: Errata, Type: Need to Publish

#1622 fix: 「ユニットテストを記述する」における軽微な typo 修正
  source/use-case/nodecli/refactor-and-unittest/README.md
Labels: Type: Errata, Type: Need to Publish

#1628 fix typo
  source/basic/class/README.md
Labels: Type: Errata, Type: Need to Publish

#1627 feat: 第2版のレビューアーへの謝辞を追加
  source/intro/README.md
Labels: Type: Feature, Type: Need to Publish
