Repository asciidwango/js-primer, pull requests merged in 2024-10, with the labels that each got.

#1766 chore(deps): update to HonKit v6
  package-lock.json
  package.json
Labels: Type: Maintenance

#1768 fix: fix typo
  source/use-case/nodecli/md-to-html/README.md
Labels: Type: Bug

#1769 chore(deps): update textlint and HonKit
  package-lock.json
  package.json
Labels: dependencies
