Repository asciidwango/js-primer, pull requests merged in 2025-05, with the labels that each got.

#1797 refactor: 静的メソッドの表記統一 と textlintルールの追加
  .textlintrc.js
  package-lock.json
  package.json
  source/basic/array/README.md
  source/basic/async/README.md
  source/basic/class/README.md
  source/basic/date/README.md
  source/basic/function-scope/README.md
  source/basic/implicit-coercion/README.md
  source/basic/json/README.md
  source/basic/loop/README.md
  source/basic/map-and-set/README.md
  source/basic/math/README.md
  source/basic/object/README.md
  source/basic/operator/README.md
  source/basic/prototype-object/README.md
  source/basic/string-unicode/README.md
  source/basic/string/README.md
  source/use-case/ajaxapp/promise/README.md
  test/summary-test.js
  textlint/textlint-rule-static-method-syntax/README.md
  textlint/textlint-rule-static-method-syntax/index.js
  textlint/textlint-rule-static-method-syntax/package.json
  textlint/textlint-rule-static-method-syntax/static-methods.json
  textlint/textlint-rule-static-method-syntax/update-static-method.js
Labels: Type: Refactoring

#1791 feat(module): ES2025インポート属性のセクションを追加
  source/basic/module/README.md
  source/basic/module/src/data.json
  source/basic/module/src/import-attributes.js
Labels: Type: Feature

#1798 refactor(map-and-set): Mapのキーとしてオブジェクトを使う例をシンプルなものに変更
  source/basic/map-and-set/README.md
Labels: Type: Refactoring

#1801 Design Doc: Iterator Helpers
  source/basic/iterator-generator/OUTLINE.md
Labels: Status: Proposal

#1805 docs: CONTRIBUTINGのライセンスのリンクを有効なものに修正
  CONTRIBUTING.md
Labels: Type: Documentation

#1804 feat: ES2025のSet Methodsを追加
  source/basic/map-and-set/README.md
  source/basic/map-and-set/set-creation-methods.excalidraw.svg
  source/basic/map-and-set/set-relation-methods.excalidraw.svg
  test/markdown-doc-test.js
Labels: Type: Feature, Lang: ES2025

#1807 feat: Map/SetにSpread構文による展開方法を追加
  source/basic/map-and-set/README.md
Labels: Type: 基礎文法, Type: Feature

#1810 chore: npm-run-all2 を v7 → v8 に上げた
  package-lock.json
  package.json
Labels: dependencies
